colors:
  primary:
    background: '#1C1C1C'
    foreground: '#d5c4a1'
  cursor:
    text:       '#1C1C1C'
    cursor:     '#d5c4a1'
  normal:
    black:      '#1C1C1C'
    red:        '#fb4934'
    green:      '#b8bb26'
    yellow:     '#fabd2f'
    blue:       '#83a598'
    magenta:    '#d3869b'
    cyan:       '#8ec07c'
    white:      '#d5c4a1'
  bright:
    black:      '#665c54'
    red:        '#fe8019'
    green:      '#3c3836'
    yellow:     '#504945'
    blue:       '#bdae93'
    magenta:    '#ebdbb2'
    cyan:       '#d65d0e'
    white:      '#fbf1c7'

draw_bold_text_with_bright_colors: false

mouse:
  hide_when_typing: true

window:
  option_as_alt: Both
  decorations: full
  title: ""
    # padding:
    #   x: 0
    #   y: 30
  dimensions:
    columns: 150
    lines: 100

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  size: 14.0
