set-option -g mouse on
set-window-option -g mode-keys vi
set -sg escape-time 0

set-option -gw xterm-keys on
set -s extended-keys on

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# vim-like pane switching
bind-key -r k select-pane -U
bind-key -r j select-pane -D
bind-key -r h select-pane -L
bind-key -r l select-pane -R
bind-key -n -r M-k select-pane -U
bind-key -n -r M-j select-pane -D
bind-key -n -r M-h select-pane -L
bind-key -n -r M-l select-pane -R

# reorder windows
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

## COLORSCHEME: gruvbox dark (hard)
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=colour235,fg=colour223

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour235,fg=colour223

# pane border
set-option -g pane-active-border-style fg=colour235
set-option -g pane-border-style fg=colour235

# message infos
set-option -g message-style bg=colour235,fg=colour223

# writing commands inactive
set-option -g message-command-style bg=colour235,fg=colour223

set-option -g status-left-length 64
set-option -g status-right ""
