[colors.cursor]
cursor = "#d5c4a1"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#d5c4a1"
yellow = "#fabd2f"

[colors.primary]
background = "#000000"
foreground = "#d5c4a1"

[font]
size = 14.0
offset.x = 0
offset.y = -1

[mouse]
hide_when_typing = true

[window]
decorations = "full"
option_as_alt = "Both"
title = ""
